version: "3"

services:
  web:
    build: .
    container_name: php_web
    volumes:
      - ./php/:/var/www/html/
      - ./conf/apache2.conf:/etc/apache2/apache2.conf
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  database:
    image: mysql
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: Skuska
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"